# Generated by Django 4.2 on 2023-04-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('student_Id', models.CharField(max_length=50)),
                ('s_loan', models.BooleanField()),
                ('b_loan', models.BooleanField()),
                ('e_loan', models.BooleanField()),
                ('security', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
