# Generated by Django 4.2 on 2023-04-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='student_Id',
            field=models.CharField(max_length=255),
        ),
    ]
