# Generated by Django 4.2 on 2023-04-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0002_alter_applicant_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
