# Generated by Django 4.2 on 2023-04-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0003_alter_applicant_email_alter_applicant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='b_loan',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='e_loan',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='s_loan',
        ),
    ]
