# Generated by Django 4.2 on 2023-04-26 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app32', '0005_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='owner',
            field=models.ForeignKey(default=507, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
