# Generated by Django 4.2 on 2023-04-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app32', '0006_applicant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='owner',
        ),
    ]
